### ISSUE TITLE
Javascript error - Header and Footer not loading and cant add or editing it.

### ISSUE THREAD

**Issue by eliquame** [atmostfear-entertainment/aegis#4]
The Error message in FSE editor: "Template part has been deleted or is unavailable: header" | "Template part has been deleted or is unavailable: footer"

**In chrome console I can see an error message via admin side**
deprecated.min.js?ver=73ad3591e7bc95f4777a:2 wp.blocks.children.matcher is deprecated since version 6.1 and will be removed in version 6.3. Please use html source instead. See: https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/introducing-attributes-and-editable-fields/
i @ deprecated.min.js?ver=73ad3591e7bc95f4777a:2

**Public side in chrome console:**
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at index.js?ver=1.0.0-alpha.1:28:19

**Comment by atmostfear-entertainment** [comment]
Hello @eliquame,

Thank you for pointing this out.

We are glad you caught this. It is important to note that since this theme is in its Alpha stage and the initial coding began a year ago, some issues like this are to be expected. However, we are actively working on updating our source code to align with the recent changes in WordPress, ensuring it is fully compatible with the most recent versions.

Additionally, we have recoded and updated the JS files. Could you please download the following two files and move them to `wp-content/themes/aegis/assets/js`, replacing the existing files:

- [animations.js](https://github.com/atmostfear-entertainment/aegis/blob/1.0.0-pre-alpha.2/assets/js/animations.js)
- [index.js](https://github.com/atmostfear-entertainment/aegis/blob/1.0.0-pre-alpha.2/assets/js/index.js)

Once you have done this, please check if the errors related to these files persist on your end. We would appreciate it if you could report back to us on your findings.

Regarding the errors you mentioned:

```html
Template part has been deleted or is unavailable: header
Template part has been deleted or is unavailable: footer
```

Can you check if you might have inadvertently deleted the template parts related to these errors? If possible, we recommend reinstalling the theme on a blank slate to see if the issue persists. For clarity, on our end, we have three installations of the theme on different environment setups, and we have not been able to reproduce the issue you are describing.

Lastly, we would like to share that we are in the process of updating our theme's entire source code to ensure we keep it up to modern standards.

Thanks for your understanding and cooperation.

**Comment by eliquame** [comment]
Hi Atmos Team!
Thanks your support. I overwritten the 2 js files, and I can see a new, another error in google chrome. :-D
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/f859adcf-baad-4085-9135-8aa029026058)

Template Parts.
I tried two method, but the problem is not gone.
I reinstalled (overwritten all) of Aegis theme and I deleted whole subdomain data and have made a clean install (new WP, new database, new theme install, but the problem is same)

I cant see anywhere the header and footer editor. Yes I can see the templates in patterns, but I cant figure out how can I set up example header 3 sticky to defult header. I cant find conditions ar any other option for it.

In some tempplates (editor) example cart, checkout and another some, I can see the header and footer section, and some templates example index, product catalog ect I only see the error message.

![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/202a2ddc-280a-4b69-a3f2-dc37d52d2a41)

![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/5d5bb253-1c54-47da-bb16-9c0b5b5d0397)

**Comment by eliquame** [comment]
Here is a REALLY FULL CLEAN install from the ZERO.
Deleted everething from the domain host
Made a new databes
Made a clean wp install
Uploaded (with the new 2 JS files) the Aegis Theme

I'm NOT made any other steps or stuffs.

Activated the Aegis theme and I have gone to editor. Here is what I have first seen.
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/19173bce-3f89-4ff9-8244-0621427f4899)

**Comment by eliquame** [comment]
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/eb3749bf-4ee0-4e0c-999a-bfc7ca7cb2bf)

**Comment by alexdeborba** [comment]
Hello @eliquame,

I have updated the animate.js file and restored the original version of index.js. A brief overview of the changes is provided below, but you might want to review the complete commits for a detailed understanding.

[animate.js commit](https://github.com/atmostfear-entertainment/aegis/commit/1ee51e561aceebbfc159d8cc363f2c8d105542e2)
- **Unused Variable Removal**: Removed unused `htmlEl` and `bodyEl` variables.
- **Debounce the Scroll Event**: Implement a true debounce function to handle the scroll event more efficiently.
- **Cache DOM Elements**: Cache the queried DOM elements outside the scroll event handler to avoid querying the DOM repeatedly.
- **IntersectionObserver**: Refactored the script to use IntersectionObserver:

[index.js commit](https://github.com/atmostfear-entertainment/aegis/commit/f47444ee3292fc4f2efafc23bdd3be74a5f1cb2f)

- **Revert**: Changes in index.js due to accordion issues.

From my side, I am no longer encountering any errors related to the two files. I did notice them when I initially investigated the issue. Could you confirm if you are also not seeing any console errors? I think that loading the script only when necessary should help prevent these errors.


In an ideal scenario, we aim to combine both JS files in a forthcoming release. This is on our radar as we refine parts of the theme and introduce new features, among other enhancements.

I genuinely appreciate your understanding and patience concerning this matter. Your keen observation and valuable feedback have been instrumental.

I am eager to hear if the updated files have addressed your concerns.

**Comment by eliquame** [comment]
Javascript error gone from chrome console, but the header and footer problem is staying here! :-(
Full clean install and database, any other plugin or theme.

![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/f0aed8e0-aba7-44cd-811e-4d12b187fa6b)

> Hello @eliquame,
> 
> I have updated the animate.js file and restored the original version of index.js. A brief overview of the changes is provided below, but you might want to review the complete commits for a detailed understanding.
> 
> [animate.js commit](https://github.com/atmostfear-entertainment/aegis/commit/1ee51e561aceebbfc159d8cc363f2c8d105542e2)
> 
> * **Unused Variable Removal**: Removed unused `htmlEl` and `bodyEl` variables.
> * **Debounce the Scroll Event**: Implement a true debounce function to handle the scroll event more efficiently.
> * **Cache DOM Elements**: Cache the queried DOM elements outside the scroll event handler to avoid querying the DOM repeatedly.
> * **IntersectionObserver**: Refactored the script to use IntersectionObserver:
> 
> [index.js commit](https://github.com/atmostfear-entertainment/aegis/commit/f47444ee3292fc4f2efafc23bdd3be74a5f1cb2f)
> 
> * **Revert**: Changes in index.js due to accordion issues.
> 
> From my side, I am no longer encountering any errors related to the two files. I did notice them when I initially investigated the issue. Could you confirm if you are also not seeing any console errors? I think that loading the script only when necessary should help prevent these errors.
> 
> In an ideal scenario, we aim to combine both JS files in a forthcoming release. This is on our radar as we refine parts of the theme and introduce new features, among other enhancements.
> 
> I genuinely appreciate your understanding and patience concerning this matter. Your keen observation and valuable feedback have been instrumental.
> 
> I am eager to hear if the updated files have addressed your concerns.

**Comment by alexdeborba** [comment]
Hello @eliquame,

It seems you might be looking in the wrong section. Can you please check under `Patterns` > `Template Parts` towards the bottom of the editor? Are you able to see both the `Header` and `Footer` there?

![Screenshot](https://github.com/atmostfear-entertainment/aegis/assets/5738223/61f61f0b-3939-41f9-bb3a-481bea946926)

It is possible that the mix-up stems from the fact that both are Patterns.

Eagerly awaiting your feedback.

**Comment by alexdeborba** [comment]
I have to admit, this situation leaves me perplexed. I recommend installing WooCommerce and ensuring you are using PHP version 7.4 or above, as it is a requirement.

I have tested across various environments but have not encountered this error. Do you happen to have an error log that might shed some light on this?

**Comment by eliquame** [comment]
We have spoken lots of about this problem in Messenger (patrikvarga)
I have tried 3 times to full clean install, with and without woocommerce but the problem is same.
Default I run PHP 8.1.24.
Now I'm tried out, installed WC, with, 7.4.33 and 8.0.30 but the error is same both PHP version.

Error log is clean, Apache error log server side) is clean.

Last idea, that I make you again an admin account and you can see your own eyes the problem. :-)

If I open the chrome console in WP admin side theme editor, you can see I have 2 errors, 404 error with header and footer

![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/defdc60d-7bbc-45f9-aded-a35c2d86f56d)

**Comment by eliquame** [comment]
Here is the error message (footer is same) from Firefox Developer edition:
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/0e2db1fa-6458-4997-af39-f1e9c802e5ec)

**Comment by alexdeborba** [comment]
You should have mentioned it was you; I was left in the dark.

Regardless, I have identified the problem. 

When you download and install the theme directly from GitHub (whether zipped or unzipped), the theme folder defaults to a name like `aegis-1.0.0-alpha.1`. Just rename it to `aegis`, and that should resolve the issue.

It seems when GitHub compresses it for download, the folder should ideally be named `aegis` instead of the longer version.

Let me know if this solution works for you.

**Comment by eliquame** [comment]
Booooooooooooom! :-D It was the Bug! 💯 🎉 :-D
Thanks a lot. Now already I can test your theme! :-D


BEFORE:
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/a59e6075-2311-4642-a797-55534419bcf5)
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/ecafd960-e333-4b7b-bb76-84bfdbc15f7c)

AFTER:
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/ce22ae1e-d093-4a74-8c41-dd6a45c2e99a)
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/8518e09e-ece6-4a3c-9573-04f984707bb9)

**Comment by alexdeborba** [comment]
I am pleased to hear it worked for you. This oversight was indeed an unexpected challenge for us.

We have since added a warning to the [Release](https://github.com/atmostfear-entertainment/aegis/releases/tag/1.0.0-alpha.1) to help others avoid this pitfall.

Thank you for bringing it to our attention, and we hope you enjoy using the theme.

**Comment by eliquame** [comment]
I never would have realized that this was the solution. because the system loaded other template files. :D
I think the problem may have arisen due to a reference path in some part of the code.

Thanks again for your help and amazing work with theme.
